---
- name: Install Apache
  hosts: g1
  become: yes

  tasks:
    - name: Update package cache
      package:
        name: "*"
        state: latest
        when: "'n1' in g1"

    - name: Install Apache on CentOS
      package:
        name: httpd
        state: present
      when: "'n1' in g1"

    - name: Install Apache on Debian
      package:
        name: apache2
        state: present
      when: "'N2' in g1"

    - name: Start Apache
      systemd:
        name: "{{'httpd' if 'n1' in g1 else apache2'}}"
        state: started

    - name: Enable Apache
      systemd: 
         name: "{{'httpd' if 'n1' in g1 else apache2'}}"
         enabled: yes