---
- name: Install HTTP Server
  hosts: g1
  become: yes

  tasks:
    - name: Install HTTPD Server on CentOS
      dnf:
        name: httpd
        state: present
      when: ansible_distribution == "Amazon" or ansible_distribution == "Debian"

    - name: Start Httpd
      service:
        name: httpd
        state: started
      when: ansible_distribution == "Amazon" or ansible_distribution == "Debian"

    - name: Enable Httpd
      service:
        name: httpd
        enabled: yes
      when: ansible_distribution == "Amazon" or ansible_distribution == "Debian"

    - name: Install Apache on Debian
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Amazon" or ansible_distribution == "Debian"

    - name: Start Apache
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Amazon" or ansible_distribution == "Debian"

    - name: Enable Apache
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution == "Amazon" or ansible_distribution == "Debian"
...
