---
- name: Install Apache
  hosts: g1
  become: yes

  tasks:
    - name: Check OS Distribution
      command: "cat /etc/os-release"
      register: os_release_output

    - name: Update package cache
      apt:
        update_cache: yes
        when: "'Debian' in os_release_output.stdout"

    - name: Install HTTP Server on CentOS
      yum:
        name: httpd
      when: ansible_distribution == "Amazon"

    - name: Install HTTP Server on Debian
      apt:
        name: apache2
      when: ansible_distribution == "Debian"

    - name: Start Apache
      systemd:
        name: "{{'httpd' if 'n1' in g1 else apache2'}}"
        state: started

    - name: Enable Apache
      systemd: 
         name: "{{'httpd' if 'n1' in g1 else apache2'}}"
         enabled: yes