---
- name: Install Apache
  hosts: g1
  become: yes

  tasks:
    - name: Check OS Distribution
      command: "cat /etc/os-release"
      register: os_release_output

    - name: Update package Lists
      apt:
        update_cache: yes
        when: "'Debian' in os_release_output.stdout"

    - name: Install HTTP Server on CentOS
      yum:
        name: httpd
      when: "'Centos Linux 7' in os_release_output.stdout"

    - name: Install HTTP Server on Debian
      apt:
        name: apache2
      when: "'Debian' in os_release_output.stdout"

    - name: Start Apache2
      service:
        name: "{{'httpd' if 'n1' in g1 else apache2'}}"
        state: started

    - name: Enable Apache2
      service: 
         name: "{{'httpd' if 'n1' in g1 else apache2'}}"
         enabled: yes