---
- name: Deploy Web App 
  hosts: n1
  become: yes

  tasks:
    - name: Git 
      yum:
       name: git
       state: present

    - name: Host Code
      git:
        repo: https://github.com/CeeyIT-Solutions/food3.git
        dest: /var/www/html
        force: yes
...